### ISSUE TITLE
Generate Android image assets

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#101]
We need:

- [x] A 512x512 icon (using the current one)
- [x] At least two phone screenshots
- [x] A 1024x500 "feature graphic"
- [ ] A 180x120 optional "promo graphic"

For the purpose of letting us test a beta build, I'm uploading a blank feature graphic and some iOS screenshots. I suspect the feature graphic should look something like the top of flappyroyale.io, but we might want to look at the Play Store to see what they're actually looking for.

**Comment by orta** [comment]
Okkkk

**Comment by orta** [comment]
![OG Preview Copy](https://user-images.githubusercontent.com/49038/59933310-1718fa80-93fe-11e9-934b-a548aacc5f4d.png)

**Comment by lazerwalker** [comment]
I've got some hand-grabbed Android screenshots in place for now – these all lives in `assets/fastlane/android/en-US`, and get pushed to the Play Store automatically on a fastlane deploy.
