### ISSUE TITLE
Standardize and tighten up royale start flow

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#105]
On both the royale lobby and trial screen, I want to change how the button works.

It feels awkward to me on the death screen that you have to wait before you can even press the button. It also feels awkward to me on the lobby screen that you can't hang out and read the list of names if you want. So:

On both screens, the button says 'ready' and is always pressable. The conceptual idea is that every live player needs to ready up before starting.

Current hypothesis: when we first show the lobby or death screen, we say "okay, it's going to take 5 seconds for all other players to ready". If you press 'ready' after that, you start immediately. Otherwise, you count down.

(Alternate option would be to say "it's always 1-2 seconds after you press", but I think quicker is better)

**Comment by orta** [comment]
cool, interested to see this

**Comment by lazerwalker** [comment]
It's live on prod. Curious to hear your thoughts, I'm personally way happier with it

**Comment by orta** [comment]
Agree
