### ISSUE TITLE
Tweak lobby designs to explain the modes

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#106]
In in-person tests, I've had a hard time explaining trial mode to people who aren't already familiar with daily trial. 

I'm going to play around with tweaking the lobby screens to have slightly longer descriptions of what the game mode in question is.

**Comment by orta** [comment]
👍

**Comment by lazerwalker** [comment]
There's a new description for trial mode. Not sure it's needed for royale.
