### ISSUE TITLE
“Best” badge logic not quite right on trial

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#110]
See screenshot. I think it’s this user’s best, but the placement is messed up. ![GitHawk Upload by lazerwalker](https://i.imgur.com/fn5mM68.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
I just came to make this issue

**Comment by lazerwalker** [comment]
Hrm, I started jamming on this before realizing that, at least in the current design, I don't know if this badge really makes sense here? 

I wonder if the badge would be legible without the "BEST" text if we put it in the whitespace between your score and your name? Although I sort of want to tighten up that whitespace anyway to give us more space for longer names.

**Comment by orta** [comment]
I think it might make sense to have down by fail for everything but coming in top 3 I think

That top bit only shows then

**Comment by lazerwalker** [comment]
Yeahhh, that makes sense.

I'm on the fence about whether we're better off also putting it down at the bottom in the top 3 case as well, just to keep it standard.

**Comment by orta** [comment]
When you're in 1st, that's definitely the optimal place (next to your score) - but I'm cool with it for 2nd+ onwards

**Comment by orta** [comment]
This is fixed
