### ISSUE TITLE
Change "lives" icon in trial mode to a heart

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#111]
I wonder if it might make sense to completely kill the ghost birds, and the top-left "what position you are!" display for Daily Trial. 

I feel like it'll help differentiate the two modes, making trial feel more like a quiet personal high score thing, as opposed to a thing you're doing with other people. From a conceptual standpoint, it also helps drive home the Royale idea that a ghost bird is an actual real live human player, since we don't really pretend in Trial mode that the ghosts are live.

Thoughts?

**Comment by orta** [comment]
Bold, but I'm not against it - let's give it a run for a beta or two

**Comment by lazerwalker** [comment]
Not sure how it'll feel, but it's in place and being deployed now.

Made sure it was a single commit so we can easily revert.

**Comment by orta** [comment]
Yeah, this feels nice - might be nice knowing the positions of the people ahead but its hard to read that corner and play

**Comment by lazerwalker** [comment]
As in, you want to know that you're currently 5th out of 15 players?

I thiiiink I like it not being there as differentiation from Royale mode? For how short a game is, I think there's something nice to saying "Royale mode is where you can get this really tight real-time feedback loop of seeing _exactly_ how well you're doing compared to anyone else at any given time. For Daily Trial, just focus on doing as well as you can, and then you'll see how you stack up when you're done."

(If we do want to re-add it, we also have to think about how it scales with a ton of players. If 1,000 people have played today's daily challenge, it feels like it'd be awkward to see "you're in 1000th place" before getting the first pipe)

**Comment by orta** [comment]
hah, I *think* we still cap the number of recorded trial games - so max of 99 but aye.

I dunno what I'm advocating for TBH, I had wondered if it would be that you'd see at least a player ahead but I don't think that makes any sense now

**Comment by lazerwalker** [comment]
Hah, right, forgot about that :D

My hope was that the top-right "here's the score/bird that's one leaderboard position higher than your current high score" would help serve that purpose. It's unclear to me yet whether it's accomplishing that goal.

**Comment by lazerwalker** [comment]
I'm feeling good about how this currently feels — @orta?

**Comment by orta** [comment]
Same, I think I want to change the lives indicator to a heart (as it's confusing that your bird is on both sides) but other than that - good to go IMO

**Comment by lazerwalker** [comment]
yeahhhh, good call

**Comment by orta** [comment]
Alright 👍 

<img width="682" alt="Screen Shot 2019-06-25 at 9 12 59 PM" src="https://user-images.githubusercontent.com/49038/60150577-21385180-978e-11e9-86aa-03ffda08bc36.png">
