### ISSUE TITLE
Safari is fuzzy

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#114]
iOS is actually fine, but desktop (demo + dev time)

**Comment by lazerwalker** [comment]
A clue: some of the birds in the chairs in the 'Training' section of the website are fuzzy for me on desktop Safari.

Almost always the entire right-most column, as well as the second-from-the-right on the second and fourth rows.

**Comment by lazerwalker** [comment]
![Screen Shot 2019-06-23 at 14 28 26](https://user-images.githubusercontent.com/821238/59976329-2bf2bb00-95c3-11e9-8dc4-6a93e0e596b3.png)

**Comment by orta** [comment]
somehow this isn't happening on the production demo https://flappyroyale.io/demo

**Comment by orta** [comment]
Same today
