### ISSUE TITLE
Create App/Play Store screenshots

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#115]
4 of em, for the media pack

**Comment by lazerwalker** [comment]
Could do this manually, could also get covered by #90.

**Comment by orta** [comment]
I think I know what I want for these as part of the marketing pack, not sure I can automate them alas - will give it a go tomorrow

I'm cool with automating the App Store ones

**Comment by orta** [comment]
App Store ideas:
<img width="523" alt="Screen Shot 2019-06-26 at 7 19 45 AM" src="https://user-images.githubusercontent.com/49038/60188492-3cce4700-97e4-11e9-8870-6c17a57ac69c.png">

**Comment by orta** [comment]
So these are in for the beta - the site wide ones.

Ones for the App Store ^ 

Those are another issue, so I'll de-milestone this and rename

**Comment by lazerwalker** [comment]
Need to upload these for Android. Can try uploading the exact same files and see if Google complains.

**Comment by lazerwalker** [comment]
Copied the same files over to the Google Play Store console.
