### ISSUE TITLE
Cap royale entrants at 99

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#116]
![Screen Shot 2019-06-22 at 7 30 14 PM](https://user-images.githubusercontent.com/49038/59970818-3d38ba80-9524-11e9-8984-8d3048eb97da.png)

**Comment by lazerwalker** [comment]
Should be fixed.

The filtering happens in RoyaleLobby and RoyaleDeathScreen, immediately after fetching scene data. Could have put it in `fetchRecordingsForSeed`, but didn't want to think through the ramifications of whether that might mess with Trial mode or anything else.

**Comment by lazerwalker** [comment]
If we find ourselves needing more functionality like this, I could see extending `fetchRecordingsForSeed` to take in e.g. a max number of replays. But YAGNI for now.
