### ISSUE TITLE
Homepage wins should be just royales

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#117]
Right now it’s both

**Comment by lazerwalker** [comment]
Should be fixed.

But this raises a related conceptual question: what *is* a Trial win?

If I understand correctly, our current "position" logic happens at recording time: if you see a Trial death screen that shows you as #1, that counts as a "win". So: if you're the first person to play a Trial run for a given day and get 1 point, then play again and get 2 points, then again and get 3, that counts as 3 wins, even if dozens of players come in and then score higher than you.

Conceptually, I think there should only be a single "winner" for a given daily Trial, and you only really know that at midnight UTC (or whenever exactly we switch over daily seeds).

I thiiink I'd advocate for:

1. For now: remove the concept of "trial wins".
2. Eventually: when you open the app, if you were the highest-scoring player for a given previous Trial day, give you some sort of in-app pop-up letting you know and rewarding you. Maybe we track that as a "win" and expose it in stats/etc.

**Comment by lazerwalker** [comment]
Closing this out in favor of the other one for discussion a out trial

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
