### ISSUE TITLE
Cache the API call for the seeds

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#120]
It could probably only make a real API request every 30m instead of on every menu, should cut the number of function calls drastically.

**Comment by lazerwalker** [comment]
Since we currently only cycle seeds on the hour, the Firebase API call is going to return a date specifying the next time the client needs to query for seed changes

**Comment by lazerwalker** [comment]
To watch out for: not sure how this will interact with client times being off by a few minutes. Might be worth proactively setting expiry to ~5-10 minutes before the hour, just in case.
