### ISSUE TITLE
Remove all references to Fortnite in copy

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#122]
The first beta build I uploaded got initially rejected by Google for containing a reference to "Fortnite" (i.e. somebody else's IP) in the metadata. Wouldn't surprise me if Apple does the same.

If we're going to rewrite description copy for both storefronts, we might as well make it consistent on the website as well.

**Comment by orta** [comment]
👍

**Comment by lazerwalker** [comment]
Updated. Both short + long descriptions are now standardized across the site and the Android + iOS fastlane repos (not synching Android til we next push a Play Store beta, and I was having trouble accessing iTC).
