### ISSUE TITLE
Make a solid reusable GIF of the game

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#125]
For social media announcements and such. Probably want something with the full UI, rather than the training video on the website

**Comment by orta** [comment]
Agree

**Comment by orta** [comment]
These are in 

https://firebasestorage.googleapis.com/v0/b/flappy-royale-3377a.appspot.com/o/flappyroyaleio-wide.gif?alt=media&token=515e7fdd-8e19-45d8-97ba-123468e145b3

https://firebasestorage.googleapis.com/v0/b/flappy-royale-3377a.appspot.com/o/flappyroyaleio-square.gif?alt=media&token=e358167e-f47a-40a1-8ca9-da1213a2222e
