### ISSUE TITLE
Site has no visual tie to it being a mobile game

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#126]
was my idea for improving that 
![Photo on 6-23-19 at 9 04 AM](https://user-images.githubusercontent.com/49038/59978877-e966b980-9595-11e9-9af7-1e6924141ea5.jpg)

**Comment by orta** [comment]
also the projector looks out of place as a vector object

**Comment by orta** [comment]
![Screen Shot 2019-06-23 at 1 55 46 PM](https://user-images.githubusercontent.com/49038/59981878-f3e97900-95be-11e9-96a1-ac033b44bbe0.png)

**Comment by mennenia** [comment]
Also prefer the new heading title ("Flappy Bootcamp") 😄
