### ISSUE TITLE
Exiting and reopening the app causes weirdness

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#130]
> Sometimes switching back into the app will cause the birds to move slowly
> And or appears to make some kind of offset
> Switch out of the game, die, wait until you would normally see play again, press play again, observe time isn’t regular

via @doctorpangloss

**Comment by orta** [comment]
I think the game isn't getting the pause notifications when the app leaves

**Comment by lazerwalker** [comment]
Right, yep. The code copy/pasted from previous projects of mine should theoretically be dispatching events to track that (https://github.com/lazerwalker/flappy-royale/blob/master/ios/FlappyRoyale/ViewController.swift#L94-L101) but a quick grep of the codebase doesn't look like we're consuming those events anywhere.

**Comment by lazerwalker** [comment]
I'm having trouble reproducing actual issues with this, which is worrying.

That said, there's code to theoretically handle it in place. Instead of using the fake custom events the iOS app was already threading through, the iOS client now sends `visibilitychange` events, which Phaser theoretically handles properly.

**Comment by doctorpangloss** [comment]
This no longer reproduces on the latest 1.0 (5) from TestFlight

**Comment by lazerwalker** [comment]
Ahhh, you rock 👍
