### ISSUE TITLE
Find some way to debounce or otherwise reduce false positives for share button

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#131]
> I think if you die and tap rapidly it shouldn’t activate the share button
> That accidentally comes up a bunch because it’s where my finger was while I was tapping

h/t @doctorpangloss

**Comment by orta** [comment]
Yeah, I want the same for ready in royale

**Comment by lazerwalker** [comment]
Ben's also advocating for removing the ready countdown in royale entirely. Which I think is potentially at least worth trying for a beta or two — I doubt it'll break the illusion for people.

**Comment by orta** [comment]
so long as it doesn't allow jumping instantly because that was the place where you jumped, I'm good

**Comment by lazerwalker** [comment]
I think the flow will be exactly the same as it is now, we'll just always start a new game as soon as you tap 'ready' instead of potentially counting down. Presumably however we fix the button presses from triggering too eagerly will fix this too

(Naive thoughts for now: don't accept any inputs for a few hundred MS after showing a death screen?)

**Comment by orta** [comment]
that's enough for me

**Comment by lazerwalker** [comment]
We now ignore button inputs for 200ms after the death screen shows. Hard to say without more user testing, but in my anecdotal testing that was quick enough that I didn't notice when trying to manually press the 'ready' button again.

Also killed the mandatory countdown.
