### ISSUE TITLE
Daily trial death leaderboard is wrong

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#132]
![GitHawk Upload by lazerwalker](https://i.imgur.com/yo9Dsul.jpg)

5 < 10!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
I might have fixed this but not deployed - deploying now

**Comment by orta** [comment]
<img width="1396" alt="Screen Shot 2019-06-24 at 9 16 33 PM" src="https://user-images.githubusercontent.com/49038/60068860-59c02880-96c5-11e9-9ef2-2452bea20241.png">

confirmed
