### ISSUE TITLE
Calculate + show "royale streak"

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#137]
I think this has no UI until you have a streak of at least 2 (e.g. the last two royale games you played, you were #1)

When that happens:
* We replace the "wins" counter on the home screen with "royale streak"
* We put a "royale streak" counter in the top-right of the royale death screen
* As soon as your streak breaks, we go back to the old visualization _(I'm not sold on this)_
* If you've *ever* had a royale streak >= 2, we add a "royale streak" row to the stats page.

**Comment by lazerwalker** [comment]
Would like to find a way to expose this in the royale lobby / death screen, but this now shows up in the stats page (both your current streak and your highest ever, if you've ever had a single win) and in the main menu (if you currently have a streak >= 0)

**Comment by lazerwalker** [comment]
Now shows this on the royale death screen (both your current + your best), iff you currently have won at least once.

We could gate all of this behind having a streak of 2 instead of 1, but I like the way this opens up the possibility space. "Great, you won once, congrats! Now keep it up?"

**Comment by orta** [comment]
ace
