### ISSUE TITLE
Use the app launch screen to mask download times

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#139]
It feels really awkward to download a new version of the game and THEN see the title screen (and also feels sort of weird that you don't see the title screen before the download screen?)

Proposed solution:

1. If there's a new version of the game to download, show the launch screen before showing the 'loading...' screen

2. Let the new version of the game start downloading during the launch screen, which will reduce the amount of time on the loading screen (we should get this for free)

3. When restarting the game post-download, don't show the app launch screen

This will also have the benefit of making the download seem faster!

**Comment by lazerwalker** [comment]
Theoretically in place, but haven't tested on prod yet. Will test next time I deploy web.

**Comment by lazerwalker** [comment]
Tested this is working as expected.

**Comment by orta** [comment]
this is clever
