### ISSUE TITLE
All birds should start at a random X, which needs to be stored in the user seed

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#14]

**Comment by lazerwalker** [comment]
Does "random X" = window position within the bus?

Otherwise, the user flapping the first time is what sets their 'starting x', yeah?

**Comment by orta** [comment]
random within the bus, I think I can store the initial x which is where they live in the bus then they get out from that point - which means it should look consistent with the pipes on screen for user

**Comment by orta** [comment]
fixed by https://github.com/lazerwalker/flappy-royale/commit/10508fe19a98b888680bff0b974a80befec954da
