### ISSUE TITLE
Other players' birds seem to be missing in menus?

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#141]
In the royale lobby and the trial death, I don't see any avatars other than my own

**Comment by lazerwalker** [comment]
Working now — might have been atmospheric noise from a deploy.

**Comment by lazerwalker** [comment]
Hrm, nope, jk.

Working consistently for me in the trial death screen now, but in neither the royale lobby nor the trial lobby.

**Comment by lazerwalker** [comment]
Can't access a phone webkit debugger while I'm at the coworking space, but will look into this when I get home (unless Orta does first)

**Comment by orta** [comment]
My attempt to remove scrollbars in windows removed the birds instead, of course. Fixed.
