### ISSUE TITLE
Position calculation in royale is too generous

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#143]
I've seen this a handful of times now.

I have a screenshot on my phone (can upload later) where the royale death screen says "fail" instead of win, there appeared to be birds alive at the moment I died, but my position is `#1`.

**Comment by orta** [comment]
might be an `<=` instead of a `<` or something

**Comment by lazerwalker** [comment]
Yeah, think this is just an off-by-one error. `position` is 0-indexed (position 0 = you won), but we also were naively displaying "you're in position `position` / `totalNumberOfPlayers`. 

So in my case, "position 1" meant I was actually in second place.
