### ISSUE TITLE
If you tap to defocus changing a name in setting you end up in a weird state

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#146]
![GitHawk Upload by orta](https://i.imgur.com/1iYE1iT.jpg)

**Comment by lazerwalker** [comment]
Argh, yep. If I don't get the chance to look at this today, here's the code that fixes this when you tap the 'done' button on the input bar: https://github.com/lazerwalker/flappy-royale/blob/master/src/app.ts#L194-L196

I had trouble binding to `blur` of the name dialog text box (as opposed to `window.blur`), so we might need to experiment to figure out what can actually trigger it.

(For the name dialog box, I just manually re-scroll when you tap the "OK" button)
