### ISSUE TITLE
Set up some kind of staging environment

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#154]
This could just be deploying to `flappyroyale.io/staging` instead but I think it will have to be a separate deploy entirely or it will trigger users having to see the loading screen

**Comment by lazerwalker** [comment]
Yeah, not sure of the implementation, but a `yarn deploy-staging` that just updates /staging makes sense to me. Easy to set up a new iOS scheme with a different icon/name/bundle ID that hits /staging instead, I already have one set up for a dev environment (and we can TestFlight it)
