### ISSUE TITLE
iPhone X, XS, XR Support/Loading Issues

### ISSUE THREAD

**Issue by truealphamc** [flappy-royale/flappy-royale#162]
![C15876E6-B783-40BA-85DC-821B354DD520](https://user-images.githubusercontent.com/18666760/60300859-f40ab100-98fd-11e9-9d27-3d757d65e06a.png)
![6A9AF6D9-4BE4-45D2-AB16-E42FF49DB7B4](https://user-images.githubusercontent.com/18666760/60300860-f4a34780-98fd-11e9-87bc-330d59df3256.png)
![7FDDAAB7-14EB-434A-969F-AC48EE76D2EF](https://user-images.githubusercontent.com/18666760/60300861-f4a34780-98fd-11e9-915b-4274fe2efa97.png)

Not sure if Its just me but the screen seems to be panned all the way to the top including the notch which exposes white on the bottom. On top of that, upon tapping royale, the screen goes blue and nothing happens. Sat there for 5 minutes and nothing changed.

**Comment by orta** [comment]
We think this is fixed due to billing and some CORS fixes we applied about 5-10m ago - thanks for the report

**Comment by truealphamc** [comment]
Can confirm it is working now! Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
