### ISSUE TITLE
Support loose and tight attire

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#17]
right now the attire is more or less a frame out of sync, this actually look _really_ good for a hat

but with anything else it's not great, so ideally want to support both

**Comment by orta** [comment]
all attire became tight in https://github.com/lazerwalker/flappy-royale/commit/b183b59baa9845f828d3d876c1775e3c162ce6b9

**Comment by lazerwalker** [comment]
I love this phrasing.
