### ISSUE TITLE
Android layout issues

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#171]
On @increpare's phone, both the top and bottom are cut off, and the system navigation bar is still shown. Will bug him to help me debug this at some point!

**Comment by orta** [comment]
when Iv'e seen it, it looks like it's only on the curved screens - maybe we need to figure out their safe area insets?

**Comment by lazerwalker** [comment]
Will want to test this on some friends' phones, but this is now working 100% as expected on my device.

Also killed landscape support, hah.

**Comment by lazerwalker** [comment]
(spoke slightly too soon, things are too high up because Android doesn't set CSS notch offsets. Waiting to push til i thread that data through from native)

**Comment by lazerwalker** [comment]
Still not totally fixed, still seeing the bottom slightly cut off on my phone after adding in the notch offset.
