### ISSUE TITLE
When you die in a trail, the "position" you are in should be the highest for that seed

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#175]
e.g. 
- game 1 - I score 20, come in pos 5
- game 2 - I score 10, come in pos 45

The trail death message should show 5 and not 45 (maybe stay "still 5") if we can?

**Comment by lazerwalker** [comment]
We got this for free with PlayFab! :D

I thiiiink our "your scores for today" display is better, but I'm not totally sure if you disagree.

I kinda like "still 5"?

**Comment by orta** [comment]
The current setup works for me
