### ISSUE TITLE
Add pretty frame to web version

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#181]
I've seen a lot of photos/videos of the web app that look janky because it's just a white page with the game in the middle.

It'll look less bare when we have ads in place, but it'd be nice to have a frame that takes up the full window. I'm tentatively imagining red curtains (can probably tint + reuse the ground sprite) framing it to look like a movie theater, and then we can even have the seated birds + projector off to the side.

**Comment by orta** [comment]
hah
