### ISSUE TITLE
Android app needs an icon

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#193]
We must be missing a format. This is all in the Play Store web UI and/or fastlane.

**Comment by lazerwalker** [comment]
Google Play Console is only missing a few assets that aren't clearly related (180x120 promo graphic,  TV banner, tablet + TV + wear screenshots). 

One email report specifically called out the Pixel 2 XL, which is a phone and not a tablet.

**Comment by lazerwalker** [comment]
I'm a dummy. We set the app icon in the Play Store, but not in the Android binary itself. This is something to do in Android Studio.

**Comment by lazerwalker** [comment]
Setting up an Android app properly requires some fanciness — the new hotness is an adaptive image with discrete foreground and background layers. 

I'm sufficiently not-Sketch-fluent that I'm guessing @orta will be able to grab a template to whip up what we need way quicker than me.

**Comment by orta** [comment]
I got this

**Comment by orta** [comment]
This is in
