### ISSUE TITLE
Set up IronSource banner/video ads on mobile

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#195]
Waiting on Mopub. Tracking here so it's in the milestone.

**Comment by lazerwalker** [comment]
They work!

Need to switch to IronSource.

**Comment by orta** [comment]
iOS has moved

**Comment by lazerwalker** [comment]
Android is working as well, showing dummy ads for both banner ads and videos.

To go live, we both need to figure out mediations, and manually contact them to switch us from test to live. Opened #241 and #242.
