### ISSUE TITLE
Set up push notifications

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#198]
Would be good to have the option as a communication channel. 

PlayFab can act as our APNS for us.

**Comment by lazerwalker** [comment]
@orta I thiiiink this is set up / working, but can't test since my test app bundle ID is different from on PlayFab. Need you to set up a production APNS key for the production app.

The steps up through uploading a .pem to the PlayFab Settings -> Push Notifications -> iOS tab. https://api.playfab.com/docs/tutorials/landing-players/push-notification-basics/push-notifications-for-ios

Thanks! :D

**Comment by orta** [comment]
uh oh, doing this in keychain crashed for me before

**Comment by lazerwalker** [comment]
beeeeeeta OSes :/

**Comment by orta** [comment]
well obviously I wasn't gonna do any thing of significance on the Mac anymore now I've got winders :D

**Comment by lazerwalker** [comment]
Basic push notif functionality is tested and working on both iOS and Android as soon as we push out new versions of both. 

Related still-open issues: #298 and #300
