### ISSUE TITLE
Spike on how PlayFab will integrate with attire rewards

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#204]
I'm pretty sure they'll be able to handle pretty much everything related to what we want to do with rewarded tiered attire gachas, so I want to wrap my head around how it works / how they integrate with our ad providers (or not) / etc.

**Comment by orta** [comment]
coooool

**Comment by lazerwalker** [comment]
Yeah, this seems straight forward. 

On the item side: we set up a catalog of items, set up drop tables with probability distributions, and then can straight-up make an API call to return a random item from a weighted bucket.

On the ad side: we can directly wire things up so that PlayFab is aware of IronSource and can grant the user account a reward only when they watch an ad: https://api.playfab.com/docs/tutorials/landing-content/ironsource

There's a question of how much time/effort is worth getting us over to a "proper" / secure system, versus the current system that's easier to build but easier for players to cheese. (Realistically, I should do the Right Thing in PlayFab for work purposes :P)

**Comment by lazerwalker** [comment]
Note to self: I think part of this is going to be taking the user's unique PlayFab ID and threading that through to native code, so that when we initialize IronSrc we can use that as the user ID.

Since setting the userID happens before we initialize ironsrc, we'll probably need to delay initializing ironsrc until after the game loads and playfab login happens.

**Comment by orta** [comment]
We're blocked on this until we get added to the ads beta

**Comment by orta** [comment]
It didn't, and I got passed through so enough hands that it went nowhere
