### ISSUE TITLE
Separate out attire settings from settings settings

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#216]
We have a whole bunch more things to cram into settings (audio and haptics toggles, dark mode, maybe moving the tutorial link there, etc). We'll also have more attire.

Probably want to separate out a "customize your character" screen (name + attire) from actual settings.

The real design challenge here is that we're running out of physical space on the main menu for smaller form-factor phones.

**Comment by lazerwalker** [comment]
Noticed @orta already did this for stats :)

Would propose moving "settings" into a gear icon that goes where the "?" icon is now, and settings has a "show tutorial" button. Top-level buttons on the menu are Royale / Trial and then Character / Stats

**Comment by orta** [comment]
Agree

**Comment by lazerwalker** [comment]
FWIW, still not sold on "Character" as the name for that button, curious if you have thoughts. 

Fortnite uses "Locker", which doesn't seem apt for us.

**Comment by orta** [comment]
Maybe `[[Avatar] YOU]` ?

**Comment by orta** [comment]
Works for me
<img width="639" alt="Screen Shot 2019-07-03 at 9 29 07 AM" src="https://user-images.githubusercontent.com/49038/60595521-2b051a80-9d75-11e9-9d91-bdd32278b118.png">
