### ISSUE TITLE
Invalid name entry should show some text

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#217]
When we reject your name (too short / inappropriate / eventually because it's already taken), we should show a text reason instead of just outlining the box red.

Just the color isn't great for accessibility, plus more possible reasons = more confusing.

**Comment by lazerwalker** [comment]
This is tricky. PlayFab gives very long description, and doesn't give us a reliable way to distinguish length from already in use from inappropriate.

Might need to do some fuzzy matching on the error message.

**Comment by lazerwalker** [comment]
A lot of our bad play store reviews are people who claim they can't get past the name screen.

I think this is what's actually happening (probably "name already taken", but could also be profanity or too short). Probably worth figuring out how to provide sensible messages here.

**Comment by orta** [comment]
I did this last nigh 👍

**Comment by lazerwalker** [comment]
*facepalm*

awesome!

**Comment by lazerwalker** [comment]
I mean, I guess that probably means the problem is something else :/

**Comment by orta** [comment]
or it was from before late last night?

**Comment by lazerwalker** [comment]
Ah, hm. There's one from today, but seems totally plausible the actual problem was earlier.

Will hold off investigating.
