### ISSUE TITLE
Style iOS wrapper app

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#22]
Right now, there are white borders everywhere. We probably want to pick a sensible background color (maybe different for top vs bottom?) and vertically center the app.

**Comment by orta** [comment]
Could we think of maybe something that is "the top" of the pipe? then we could bottom align the canvas and have a consistent sky of sorts

**Comment by lazerwalker** [comment]
My current thoughts:

* Vertically center the main game view
* Above the game view, there are white clouds up to the top of the screen
* Below the game view, there's more of the existing ground texture (plus an ad)

There's room to have fun with this — if we want to spend time making some one-off art assets, we can have things like bird skeletons, buried treasure, etc that occasionally show up deep underground.

**Comment by lazerwalker** [comment]
FYI, I'm jamming on this

**Comment by lazerwalker** [comment]
Things I'd like to do:

- [x] Menus work across all screen sizes
- [x] HTML menus have properly positioned and sized footers
- [x] Game goes all the way up to the notch
- [x] Confirm my notch code doesn't muck up things on non-notch devices (`padding-top: env(safe-area-inset-top);`)
- [x] In game, floor extends all the way to the bottom
- [x] In game, the playable area is vertically centered
- [ ] In game, there's a "clouds" area above the playable field that scrolls with the game (and has a clear ceiling)
- [ ] Trial/royale headers are sticky
- [x] Position main menu buttons relative to device size

**Comment by lazerwalker** [comment]
Okay, a whooooole bunch of work here.

<img width="1440" alt="Screen Shot 2019-06-11 at 13 08 14" src="https://user-images.githubusercontent.com/821238/59267455-99f5c480-8c4a-11e9-9e76-cc899fee7f10.png">

The game should now properly take up the entire screen across all (iOS) devices!  The in-game width is always a fixed 160pt, so no devices can see farther ahead. Pipe hole generation is also fixed at only generating pipes within 240pt of the ground — taller devices can flap higher, but I don't think(?) that grants them any in-game benefit.

If folx disagree, we can add in a cloud layer to act as ceiling.

Let me know if you run into unexpected behavior here, this is a whole lot of changes, and I bet there are bugs lying around somewhere (the code to make the game span the notch is particularly nasty)
