### ISSUE TITLE
Settings page should show build number

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#225]
Could be useful for debugging.

Presumably two numbers, a web build as well as a native build.

**Comment by orta** [comment]
👍  good thinking

**Comment by orta** [comment]
Web + iOS side: 43f09cb

Needed changes for `window` for Android:

```
window.appVersion = '\(appVersion)';
window.buildVersion = '\(bundleVersion)';
```

**Comment by lazerwalker** [comment]
In for Android.
