### ISSUE TITLE
Add "link with Game Center / Google Play" option in settings

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#227]
Would be very little integration work (a single PlayFab method, plus either a little custom native work or integrating PlayFab native SDKs), and would give us profile syncing across devices for free.

Low-priority, as we don't currently properly support tablets, but /shrug

**Comment by lazerwalker** [comment]
If we don't do this initially, and later decide there's a valuable reason to do so, the standard f2p thing is to give people a reward to do so. Could give out custom AirPods / Google Glass attire :P

**Comment by orta** [comment]
hah

**Comment by lazerwalker** [comment]
A LOT of Android games I've tried automatically sign you into Google Play Games.

Might be worth pushing to get automatic sign-in (as in, by default / not being in the settings) for both Google Play Games and Game Center.

It'll get us nice names to prepopulate the "enter your name" prompt, and might eventually get us a social graph if we want to show you friend leaderboards. Not sure what else it gets us.

**Comment by lazerwalker** [comment]
Realized that implementation of this will also require user data synching, as it'll be bad/confusing if the same PlayFab user has a different display name / attire across different platforms.

PlayFab lets us store an arbitrary data blob on a user object. Presumably we want to persist the UserSettings blob to that, and come up with what our sync strategy is if what's on the server doesn't match the client.

**Comment by lazerwalker** [comment]
Even though Game Center isn't working yet, current users will now sync data with PlayFab. See 79d6532191721d9cd2788e6e9766e5a001118112, 8273319e53e7f177e0a007cc13217cbefe2d3a53.

If you delete the app and re-install it (or `localStorage.removeItem("settings")`), we'll automatically re-set your appropriate avatar and display name, and not show the tutorial if you've seen it. (Only mobile, not web).

There's also now a brief pause on the main menu while we wait for PlayFab auth to complete before showing the menu. This might need to change as Game Center integration takes more time to complete.

Worth noting: right now we overwrite localStorage with server data. This means if you change your attire while you have no internet access, you'll lose those changes. We can be smarter about that later, but I assume bigger avatar changes are coming, so I didn't put in a lot of effort there.

**Comment by lazerwalker** [comment]
Game Center integration lives in the `game-center` branch. Giving me 500 errors on PlayFab's side, I think there's an issue with the way I'm converting Game Center's `Data` objects into PlayFab's strings.

Gonna open an issue in the Playfab support forums.

**Comment by lazerwalker** [comment]
The `google-play-games` branch has an implementation of Google Play Games that works to the point where the client has everything it needs to log into PlayFab, and a broken implementation of Game Center. What's missing:

1. Game Center needs work (see above notes — data _should_ be good, but PlayFab's login method fails out)

2. I'm not yet actually calling `LogInWithGooglePlay`, although this is a 1-line codefix

3. We need to handle upgrading existing users. I think I have notes in the code itself, but the process looks something like:

- If the user has already logged in previously on this device, use existing login (`LogInWithAndroidId` or `LogInWithCustomId`), then call `LinkWithGooglePlay`.

- If that link succeeds, set a flag or something so that future logins use `LogInWithGooglePlay` instead

- If the link fails because that Google Play user already has a PlayFab account, we don't need to bother linking an account. Log out of the existing on-device AndroidDevice or Custom account, and instead always `LoginWithGooglePlay`.

Don't know when I'll get to this, I'm feeling too burnt out right now to do fiddly things like this that aren't on the critical path, but this is here.

**Comment by lazerwalker** [comment]
See #304 and #305 for separate Game Center / Google Play issues.
