### ISSUE TITLE
Android buttons are weirdly nonresponsive

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#228]
Both HTML and in-engine buttons need a number of taps before they register a tap event.

We've had a bunch of people complain they couldn't tap the first 'ok' button. Wonder if this is the same problem.

**Comment by orta** [comment]
o.0'

**Comment by lazerwalker** [comment]
This was me, the touch handler I added to handle the navigation bar was consuming touch events 🤦‍♀ 

Unclear if there's still an issue with the 'OK' button.
