### ISSUE TITLE
Let iOS app work (or "work") if the user has never had internet access

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#23]
Once #19 is done, we'll cache downloaded builds of the game.

But if the user opens the app for the first time with no network connection, right now nothing will happen.

Two options:

1. We include a cached build of the game they can play

2. We display a dedicated screen saying "hey, you need network connection to get the latest data" and don't let them do anything.

I thiiink the latter makes more sense, it'll be easier and I'm okay saying we dont' care about this usecase too much.

**Comment by orta** [comment]
Sounds fine to me, the app can then be real small

**Comment by orta** [comment]
If we switch out swift from the iOS app then the binary can be under a 1mb?

**Comment by lazerwalker** [comment]
Yeahhh, makes sense to me!

**Comment by lazerwalker** [comment]
Building in the infrastructure to say "if the app's never been cached, load this local HTML page instead" should be mostly the same work as dropping in a pregenerated build anyway, so this is also something we can easily revisit if users are mad.

**Comment by lazerwalker** [comment]
I'm feeling meh about taking the time to design and build a discrete HTML screen for an edge case like this, so for v1 I'm going to just pop an alert dialog if we hit this situation.

**Comment by lazerwalker** [comment]
This is driving out some other weirdness about how our loading is sometimes not worknig properly (e.g. showing a loading screen below the rest of the game)

**Comment by orta** [comment]
works for me

**Comment by lazerwalker** [comment]
Did some rudimentary tests, and this seems to work. 

If you open the game with no internet access, it yells at you. If you get access then click "try again", it works.

If you immediately close, lose internet access, then reload, it gets into a weird state, but if you've been playing for a while before doing that then it works fine as before with a cached version (I think webcache is saving behind the scenes, which takes 10-15s, and you're fucked if you close before that).

There's room for improvement, but I think I"m okay with this for now.
