### ISSUE TITLE
App doesn't do a clean start often enough on Android

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#238]

**Comment by lazerwalker** [comment]
So, the issue is that, anecdotally, most restarts of the app for me on Android are ones where the app was already open.

Worth confirming whether this will be the case for normal users most of the time.

We want to hard restart the app frequently to download new code!

**Comment by orta** [comment]
Could we trigger the download in the BG on new sessions etc?

**Comment by lazerwalker** [comment]
Yeah, that makes sense. I think if we figure out how to manually trigger a new download (...just window.reload()? something fancier?) then we can play around and see if we want to do it in the background, or on resuming the app (maybe we track when the user last exited and reload if it's greater than some threshold), or ???

**Comment by lazerwalker** [comment]
So, two thoughts:

1. On both iOS and Android: let's say part of our deploy includes uploading a static text file in a known, not-changing location, containing just the SHA of the latest deploy. Whenever the native app gains focus from the background, we grab that file, and force a reload if there's a new build of the app.

2. Separately, If we can actively download a new bundle in the background, that sounds awesome.

For 1, that still means Android players won't see the title screen as often, but as long as they're not missing out on app updates and e.g. the app isn't getting slow over time, I think that's fine.

**Comment by lazerwalker** [comment]
Okay, this is helpful rubber-ducking.

We have a separate issue, #243, that's about how Android doesn't properly pause the app when it's blurred. However, I don't think it's really meaningful for somebody to exit out of a royale mid-game and then expect it to still be there when they get back? An alternate thought:

1. When the app loses focus, we store a timestamp, and what screen the player was looking at.
2. When the app gains focus, we generally reload the window. If it's been shorter than 5 minutes, we manually suppress the splash screen (this logic already exists for if we've downloaded a new build). If it's been shorter than 30 seconds _and_ the last screen was a death screen, we consciously do nothing.

This de facto fixes #243, ensures users always have the latest build of the app, doesn't annoy them by showing the splash screen too often, and the last bit of logic makes sure that somebody who just ducks out of the app for 10 seconds and comes back isn't surprised by not seeing the results they were just looking at.

**Comment by orta** [comment]
Last/this week I added in-game code to outright kill you if you leave the focus, so that shouldn't be too much of an isssue at least

**Comment by lazerwalker** [comment]
I've noticed that if I close the Android app while the royale lobby countdown is going, when I reopen the app I'm in the bus and still alive, but the enemy birds are already X seconds into their replay.

**Comment by orta** [comment]
probably isn't being triggered

https://github.com/lazerwalker/flappy-royale/blob/19cd91355f80f72c2e4aab765bf1f3bb8ce52d24/src/battle/Scene.ts#L216-L217

**Comment by lazerwalker** [comment]
Right, that makes sense.

We could probably put a check at the start of a BattleScene of whether `window.hidden` is true, and that would make sure the round doesn't start at all if the game is blurred, and that would sort out that specific issue.

To take a step back, I thiiiink saying "when the app re-focuses, if it's been closed for ~5 minutes, force a window.reload()` still makes total sense. We can think about what the behavior should be for < 5 minutes (or whatever the boundary ends up being), and whether that includes properly sorting out resuming exactly where the player was.

**Comment by orta** [comment]
I agree

**Comment by lazerwalker** [comment]
Leaving #243 to deal with on its own, but now any client will force restart itself if it's re-focused after 5 minutes of inactivity.

This includes e.g. web browser tabs sitting in the background. Which could be undesirable behavior, but I think is okay for an overcorrection for now — we're still getting recording data being uploaded from clients who haven't updated in over a day.

I think 5 minutes sounds like the right time period?

**Comment by orta** [comment]
Aye
