### ISSUE TITLE
Exploration: Sets of bases/attire

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#248]
<img width="703" alt="Screen Shot 2019-07-06 at 4 25 39 PM" src="https://user-images.githubusercontent.com/49038/60760886-bb0fc200-a00a-11e9-8c43-f62f66e8c5c1.png">

/cc @ashfurrow

**Comment by lazerwalker** [comment]
Coool! 👍

_Really_ like the left-side attire display / easy removal, way more intuitive than the current behavior if you have 3 selected.

I'm guessing the top colored bits are tabs, and your BG color note is saying the active tab is yellow? They could probably look a lil more tab-like, but that could also be a case if it being harder to read in a static image than in motion.

For locked items: I suspect we want to sort the list so locked items are always at the end. Might also want to play with making the cell background a bit darker for locked items so they're more visibly different than just being B&W + the corner icon.

**Comment by orta** [comment]
Revised!
<img width="484" alt="Screen Shot 2019-07-06 at 6 19 48 PM" src="https://user-images.githubusercontent.com/49038/60761640-aaffde80-a01a-11e9-8d07-cedd104d02e8.png">

**Comment by lazerwalker** [comment]
I'm guessing the text at the bottom is the title / credits for the current set? It doesn't particularly read to me right now, either as a title or as a byline

Prescriptive suggestion: 

1. Move the title up below the tab bar but above the bases
2. Make the title for each pack fit on one line: e.g. "Starter Pack" / "Food Pack" / etc
3. Make the bottom explicitly say something more like "art by [Orta/Em/Zach]"

**Comment by lazerwalker** [comment]
I also still think the disabled state for locked attire isn't quite as differentiated as I'd like (I'd personally try putting e.g a ~30% black layer over the entire cell), but that's also easy enough to tweak later if it gets implemented as designed.

**Comment by orta** [comment]
Good feedback!

<img width="465" alt="Screen Shot 2019-07-07 at 12 02 09 PM" src="https://user-images.githubusercontent.com/49038/60770980-11ced780-a0af-11e9-8ed6-16838ae9f699.png">

**Comment by lazerwalker** [comment]
👍

**Comment by orta** [comment]
This is in

**Comment by orta** [comment]
This is in
