### ISSUE TITLE
Hook into the reviews function in android 

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#252]
https://github.com/lazerwalker/flappy-royale/blob/a314cc542184cf34e87f80bcd39ec82b9fc4cd17/src/nativeComms/requestReview.ts#L1

**Comment by lazerwalker** [comment]
Also see https://github.com/Vorlonsoft/AndroidRate (via #62), in case that's helpful

**Comment by lazerwalker** [comment]
Pulling in AndroidRate (and not using any of their display logic, just forcing them to show) so we can avoid having to design our own modal "you should rate us!" popup.
