### ISSUE TITLE
Fix attire rotation

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#254]
Attire in my head is always aligned at 0.5, 0.5

<img width="615" alt="Screen Shot 2019-07-05 at 11 07 47 AM" src="https://user-images.githubusercontent.com/49038/60770912-5312b780-a0ae-11e9-9efb-83c163eba490.png">

That's how it is in menus etc, but in-game it's actually different and that makes it real hard to folks producing Art to have any predictability

**Comment by lazerwalker** [comment]
I'm guessing if we do #231 we'll get this for free (at least for tight attire)

**Comment by orta** [comment]
This is in via containers
