### ISSUE TITLE
Royale names are sometimes undefined

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#260]
Places to check:

- Look in Playfab to see if we have users with no displayname set
- Check in the client if there's some reason we'd be rendering 'undefined'
- Check the replay upload and migration scripts to see if there's some way we'd be setting bad data

**Comment by lazerwalker** [comment]
In uploadReplayForSeed, sometimes the request from PlayFab has no name. Those users are now being stripped out, and there's logging in place (on Fb cloud functions) we can investigate later.

**Comment by grivkees** [comment]
I think I just hit this. Here’s some details on what I was doing:

I opened the game, everything was fine. I reviewed the “you” and “stats” tab. Everything looked good and my username “G” was showing.

Decided to do the daily trial. Leaderboard showed only one bird (named a1a I think) with a score of 3, nothing else. I did a run of the daily trial and got more than 3, it told me I was the highest scorer. The leaderboard showed up and in first place was my bird and the name “undefined”. The only other bird listed was the bird with 3 I saw before I played.

I hard closed the app at this point (I realized something was wrong and figured a restart would help). When I reopened the game I got the NUX and a username selection prompt, and I wasn’t able to get back in with my same username. 

It sounds like somewhere in this flow the game logged me out or forgot who I was. Hope this helps narrow it down!

**Comment by lazerwalker** [comment]
Ahh, thanks, this is super helpful.

@orta so the problem here is that we didn't update the API version number. People running ancient beta versions of the app (who are talking to the old Playfab titleID) are still sending in replay data for production seeds. The good news is that means the server-side undefined name check should be sufficient.

@grivkees so you know a bit about what's going on: as we've been gearing up for a proper production release, we switched the app over to a different server, which included things like a one-time wipe of everybody's data and also setting some restrictions on usernames (such as, unfortunately, that they need to be at least 3 characters long). We have code in place to auto-update the app to the new version, but there have been a number of bugs on both iOS and Android that we've had to iron out to get that working smoothly. Of course, the problem with pushing out updates to fix your updating code is that some clients get stuck on very old versions, which is what happened here :)

Thanks for writing in, this has been super-helpful for me figuring out what's going on!

**Comment by lazerwalker** [comment]
Which is all to say: the experience is going to continue to be a bit janky for some beta users, but I'm now confident this isn't an issue with the latest client + server code, and the server fixes we have in place should mean this won't happen to new users.

**Comment by orta** [comment]
Great 👍

**Comment by grivkees** [comment]
Awesome! Glad I was able to help!

Thanks for sharing details on what the issue was. It’s very cool you’re developing this openly on GitHub.
