### ISSUE TITLE
Synchronize local user stats with PlayFab

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#261]
On login, we get sent down all User Statistics. Those should wipe away local stats. These should match what we have locally, as I believe we were sending these all to the server at the point we switched to the production Playfab app.

If there are things that require local computation, presumably we could have a Playfab cloud function that does calculations at write-time.

**Comment by orta** [comment]
Those local stats can get _massive_ (they're gzipped locally because I was hitting the cap of 5mb in local storage ) so be wary of relying entirely server side data transfer

**Comment by lazerwalker** [comment]
Server isn't storing replays, it's just storing raw numbers. e.g. every time you play a Royale game, it increments "GamesPlayed" and "RoyaleGamesPlayed" by one.

So the real catch here is, if we're going to be using a server that can't reconstruct perfect historic data, we have to be forward-thinking about what data we care about capturing.

**Comment by lazerwalker** [comment]
FYI: https://github.com/flappy-royale/flappy-royale/blob/master/src/playFab.ts#L126-L133

These are all PlayFab "statistics", which are the same data structure that power leaderboards.
