### ISSUE TITLE
Make attire PlayFab syncing script actually run locally

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#267]
`uploadAttireCatalog.ts` has some helper functions to sync the local attire sets defined in TS to PlayFab's inventory, but it currently relies on our webpack setup and can't easily be run as a script.

It should be something we can run as a script, so it can be run e.g. automatically on `deploy-web`.

**Comment by orta** [comment]
I'm not offended if this is in `src/scripts`- could maybe move all of them there/

**Comment by lazerwalker** [comment]
yeahhh that's a 👍 idea.

**Comment by lazerwalker** [comment]
This still turned out to be more trouble than it's worth.

For now, it lives as an exportable function in `src/scripts` – when I want to run it, I just paste the one-liner into `app.ts` someplace that runs on pageload.

**Comment by orta** [comment]
[insert a 10x programmer joke here]
