### ISSUE TITLE
Style "locked" attire like in the mocks

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#268]
I've got color desaturation in place, but given I'm focusing right now on getting the server-stuff working, couldn't be bothered to properly set up the background or the lock icon.

**Comment by orta** [comment]
![Screen Shot 2019-07-17 at 12 01 42 AM](https://user-images.githubusercontent.com/49038/61346271-11101100-a826-11e9-8a46-cb3f94402a6d.png)

locks indicate rarity too
