### ISSUE TITLE
Incompatible with the version of NodeJs 10.

### ISSUE THREAD

**Issue by EliuFlorez** [flappy-royale/flappy-royale#276]
Version 
yarn: 1.17.3
node: 10.0.0

**Error:**
`$ yarn start
yarn run v1.17.3
error flappy-royale@1.0.0: The engine "node" is incompatible with this module. Expected version "8". Got "10.0.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by orta** [comment]
Yep, that's on purpose, we're all using 8.x to work on 👍 

There might be a way to ignore the engines if you want to `yarn install`

**Comment by EliuFlorez** [comment]
Temporary solution to install

```
yarn config set ignore-engines true
yarn install
yarn start
```
but it still has an error when initializing the scripts

**Comment by orta** [comment]
This repo won't compile for anyone but [us I'm afraid](https://github.com/flappy-royale/flappy-royale#setup)

**Comment by EliuFlorez** [comment]
Oh, okay. I just wanted to help and try the scripts. :D

**Comment by orta** [comment]
:D thanks for trying!
