### ISSUE TITLE
Update flow is still kinda fucked

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#277]
Just opened prod on my phone (1.0). I saw the update screen, no launch screen, and was kicked to the main menu before the update completed. Closing and re-opening the app gave me the proper flow (splash screen -> full update screen -> main menu).

**Comment by orta** [comment]
Yeah, I feel like the JS updater is just indeterministic

**Comment by lazerwalker** [comment]
Orta thinks this is fixed!
