### ISSUE TITLE
If you uninstall the iOS app and reinstall, you lose access to your account / name

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#278]
This is currently expected because of the device identifier we're using (See #275 for some, but not all, context).

Potential fixes:

- Investigate whether using the Keychain or something else to store our ID would let it persist across uninstalls

- Add Game Center support

Game Center is the correct answer, but more work.

**Comment by lazerwalker** [comment]
Steps to ship Game Center:

- [x] Add iTunes Connect support for Game Center on the prod app
- [x] @orta enables Game Center in the Xcode project production target "capabilities" (I can't do this without a valid cert)
- [ ] Deploy Game Center JS code (on master)
- [ ] Open a PlayFab support issue to figure out how to switch to secure login [#280]

**Comment by lazerwalker** [comment]
Same thing is happening on Android (installed, picked a name, uninstalled, needed to pick a new name). Might push to get Google Play Games in now as well.

**Comment by orta** [comment]
Are you sure you can't do the capabilities thing? Looks done for me

**Comment by lazerwalker** [comment]
Ah, that would make some sense if it already worked on a machine with a valid cert.

I’ll send you an IPA when I’m back at a computer, deploying to TestFlight will be the easiest way to test.

**Comment by lazerwalker** [comment]
Yeah, we should be good. The error message I'm getting is just that it can't verify if the app ID has Game Center enabled, which (a) it does and (b) makes sense it'd give me that if I don't have a valid cert.
