### ISSUE TITLE
Stop players from being able to get loot boxes unless they have a consumable item assigned by uploadReplayData

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#292]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
This is clever, current implementation is to just give it and "surprise" if you kill the app and get back in you can skip the ad. 

I took a quick look, maybe we can make 2 items for every item? A consumable that generates the full one? Didn't quite see a way to do that part entirely on their side.

**Comment by lazerwalker** [comment]
I was just imagining that `uploadReplayData` would give you e.g. a "gold egg token" item (not exposed to the user, just under the hood), and then `openLootBox` doesn't do anything unless it's capable of consuming a "golden egg token" (or other token, etc).

This doesn't solve the problem that killing the app to skip the ad would work. Does closing and re-opening (but not force-quitting) the app cause the video to not come back?

**Comment by orta** [comment]
I think it does, we'd use the ad callback to consume it and its existence to show the egg modal
