### ISSUE TITLE
Communicate to the user what sort of egg they got before they open it

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#301]
Proposal:
"You found an egg!" -> "You found a [bronze/silver/gold/platinum] egg!". The flapping egg sprite is colored to match the name (and if it's easy to do with Phaser's text module, the word describing the type is changed to the correct color).

In an ideal world we'd have a more descriptive line of text saying something like "contains 1 rare piece of attire", but it's not obvious to me we have the screen real estate.

Things to discuss: how do we feel about those tiers? Is there a better set of 4 with less color ambiguity, given 'platinum' might be hard to differentiate from 'silver'?

**Comment by orta** [comment]
bronze/silver/gold/neon I can get on board with?

**Comment by lazerwalker** [comment]
👍

**Comment by orta** [comment]
not sure if we can change the text color at all (it's a bitmap font for which I shipped black and white only)

**Comment by lazerwalker** [comment]
yeah, shrug, totally fine with that

**Comment by orta** [comment]
It's in
