### ISSUE TITLE
Move away from PlayFab inventory

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#311]
Playfab free tier has a limit of 100 on any individual user's inventory.

We can store what inventory they've unlocked in a JSON blob in UserData, which we have a ton of. We're already fetching UserData in many places, so this won't incur extra network traffic.

I think this is technically client-writable, which means it's easier for users to fake this. There maybe a way to turn that off.

Definitely do this for actual unlocked inventory. We might be able to get away with leaving unopened eggs as consumable items, but then we need to make sure we're sweeping away old eggs.

**Comment by lazerwalker** [comment]
Okay, not diving into this today like I was hoping, but to outline the giant refactor plan that incorporates this:

- [x] Unlocked attire IDs are stored in UserData instead of Inventory (I have a draft of this, including migrating user data over from the latter to the former on login)
- [x] On game end, the egg generation logic happens locally instead of on the server. No egg logic happens, we just display it
- [x] The loot box unlock function doesn't check inventory for eggs, it just takes in a lootbox type and blindly assumes success.
- [ ] Manually go through and wipe anyone's inventory who has over 100 inventory items (and/or write a script). Make sure that, if this happens, those users get their inventory manually migrated first

**Comment by orta** [comment]
I'd assume the playfab json blob isn't infinite, it could be worth giving all attires a unique numerical ID and saving that in there?

**Comment by lazerwalker** [comment]
Hmm, good point!

Looks like we get 10kb total per user, we're currently around 1.5-2kb per user.

**Comment by lazerwalker** [comment]
I thiiiiink this should work (just using strings, not numeric IDs) but haven't pushed yet. 

Requires coordination between a web push and a server push, as the server changes will break old web clients. Later today or tomorrow, will push both simultaneously and immediately monitor.

**Comment by lazerwalker** [comment]
Seems fine. Haven't manually gone through to clear out inventory yet.
