### ISSUE TITLE
When trying to switch to a locked item, show a modal prompt explaining how to get it

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#315]
We've gotten a bunch of feedback that people don't understand how to unlock things.

**Comment by lazerwalker** [comment]
Urgh, this is a pain because we can't show modal prompts on top of HTML form views. Under current code, this would mean popping back to a background scene, which would also trigger a network "update attire" request.

Throwing in an alert for now, which won't work for Android.

**Comment by orta** [comment]
It could shake?
