### ISSUE TITLE
Cannot change bird apart from starter tier

### ISSUE THREAD

**Issue by AbCStern** [flappy-royale/flappy-royale#329]
I havent found a solution for that issue yet.
I cannot change the bird into one from the other tiers.
After change, it looks alright but when getting into a match (or into the "you" menu again) it set back to the last bird from starter tier.

Platform: Android
Device: Pixel 3
App: 1.3 r16

**Comment by orta** [comment]
This should be fixed now I think with a82b5af3c84b631b0515899c8708f5cf6106ac82
