### ISSUE TITLE
Hook up firebase native libs to the JS runtime

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#33]
For example analytics and probably admob

**Comment by lazerwalker** [comment]
Poking at getting the Firebase SDK set up on iOS.

Will eventually need to do Android separately, and also figure out what APIs we want to expose, but at least for now I can configure a firebase app and pull in the pod.

**Comment by lazerwalker** [comment]
iOS app now has CocoaPods, and sets up Firebase on app launch. Not doing anything with it yet.

Think the next (parallelizable) steps are:

* Writing up a strategy for what things we care about tracking, leading to figuring out what our JS API should look like
* Setting up an AdMob campaign, and figuring out if we can show ads in web-land or if we need to touch native view rendering

**Comment by orta** [comment]
Things I'd like to know:

- how many games are being played (also game mode: royale vs trial)
- In trial, how many times are people opting to watch a modal instead of leaving for extra lives
- which items of attire are most used
- number of total users
- number of active users

**Comment by orta** [comment]
So I think AdMob _has_ to live in native land, there are no web bindings

**Comment by lazerwalker** [comment]
Yeah, the thing I'm not sure for banner ads is if e.g. we'll be able to get an HTML string to inject (unlikely, but maybe possible?) or if they're just going to give us an opaque UIView to display.

Almost certainly the latter for interstitials.

**Comment by orta** [comment]
wrapped up in 4a0f5e5
