### ISSUE TITLE
Create a subset of the game for web

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#34]
So far that looks like removing the trial mode at least

**Comment by lazerwalker** [comment]
To fold in discussion from iMessage: making this as minimal as possible is okay. The main goal here is to get people excited enough to download the native app, while being compelling enough to minimize the chance that somebody will make a web-based clone that gains popularity.

**Comment by orta** [comment]
This is going to be at https://flappyroyale.io/demo
