### ISSUE TITLE
Investigate this error message

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#38]
<img width="476" alt="Screen Shot 2019-06-05 at 12 16 16 PM" src="https://user-images.githubusercontent.com/49038/58972537-c5c90400-878b-11e9-92db-3c9bf0780d34.png">

It's when we kill a battlescreen. Clicking any main menu button triggers it. Likely to do with the space bar input check.

**Comment by lazerwalker** [comment]
My solution feels like a bit of a hack, and I don't understand what's going on under the hood as well as I'd like, but I feel fairly comfortable this is something that isn't actually affecting the game anyway so /shrug

**Comment by orta** [comment]
This is totes fine with me 👍
