### ISSUE TITLE
Add Waiting Room

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#4]
We want a loading screen to (a) mask the fact that we need to load data from Firebase and (b) make it seem like there are humans there.

Current idea:

- Start a new game every minute
- You hang out in a waiting room, like the waiting area in a normal battle royale
- In the waiting room, you can flap around wildly. When you hit a wall, you change directions
- Add more AI bots flapping around until it's 'launch' time

**Comment by orta** [comment]
Everything but the bird stuff is in, but there's a question of what to do on that page
