### ISSUE TITLE
When you die in royale, show the results

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#42]
The designs aren't entirely done yet, but they're pretty on point

**Comment by lazerwalker** [comment]
This should also include a "play again" button that immediately re-queues you, but I haven't seen your designs yet so dunno if this should be a separate issue or no

**Comment by orta** [comment]
I think we can just add another button at the bottom - will have to make a share icon instead of the word share to make that work

**Comment by lazerwalker** [comment]
Yeah, my instinct would be that the current "share" button becomes a "Play Again" button (or some better verbiage), and a share button goes above or to the right of it

**Comment by lazerwalker** [comment]
Also, it's expected the share button doesn't currently work?

My imagination for it it is it'll pop a native iOS share sheet with a screenshotted version of the death screen. Stretch goal is right before we do [whatever it is we do to grab that screenshot], we CSS-remove the replay/back/share buttons to make it prettier.

**Comment by orta** [comment]
The share button does work on safari, and is said to work on mobile chrome/safari (whether it works in our native app wrappers is a different thing though)

**Comment by lazerwalker** [comment]
Aha, tried in desktop Safari and it worked.

Besides not working in our native app wrapper, I still think this is infinitely more compelling if we can figure out how to screenshot or otherwise add an image.

**Comment by orta** [comment]
Yeah, this support is gonna have top get built in the native app I think - but yeah, would like that

**Comment by lazerwalker** [comment]
The results screen uses HTML, yeah? 

If not, we could presumably just use https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by lazerwalker** [comment]
Split out share button functionality stuff (rather than placement) into https://github.com/lazerwalker/flappy-royale/issues/52 and https://github.com/lazerwalker/flappy-royale/issues/53

**Comment by orta** [comment]
Cool, calling this done now that share is separate
