### ISSUE TITLE
Scrollable pages should use momentum scrolling

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#43]
My naive first approach (https://github.com/lazerwalker/flappy-royale/commit/0787717aa1d124b3527072a4a8ecb66c3293d900) didn't work exactly as planned — the purple bottom bar was showing up behind, instead of in front of, scrollable content, but scrollable content in that position wasn't tappable.

Also tried applying it to just one specific `.screen` in the inspector, had the same issue.

**Comment by orta** [comment]
the feel is drastically improved though on device

**Comment by lazerwalker** [comment]
@orta if you're curious, this was the fix: https://github.com/orta/flappy-assets/blob/366f5e840a155c65a4f34328ca0dbf5316b575d8/html/Settings.html#L170-L171
