### ISSUE TITLE
Add death screen for Trial mode

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#47]
Besides your score/ranking, we want to make a big deal out of you losing a life.

We probably also want a big "play again" button. (We arguably also want this for Royale mode?)

**Comment by orta** [comment]
I think it's probably only worth doing this when you run out of lives, the quick iteration is kinda nice in trial IMO

**Comment by lazerwalker** [comment]
I think there’s a lot of value in giving people a half-second to breathe, provided there’s an easy large “start again” button. 

I also found it particularly dissatisfying when I set the global high score, but the game didn’t give me any recognition when I died and it just immediately started again. 

I’m not saying we absolutely need something here, but I’m going to prototype something so we can see how it feels. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
ace! Yes

**Comment by orta** [comment]
maybe the royale death scene and just be re-used for this TBH

**Comment by lazerwalker** [comment]
Current design:

<img width="530" alt="Screen Shot 2019-06-13 at 12 49 07" src="https://user-images.githubusercontent.com/821238/59426913-af4d2900-8dd9-11e9-86ed-fb492ca260be.png">

Shows the 'best' medal if it's your personal high score. Will say "You're #1!!" instead of Splat if you're, uh, #1.

"Again" is replaced with the same "+5 attempts" prompt if you're out of lives.

Things I'd like to ideally add in here:
* A "see leaderboard" button, instead of making you go all the way back to the main menu
* What the #1 score is, and what their name is
* What the score 1 position above yours is ("just get 3 more points to overtake Orta!")

**Comment by lazerwalker** [comment]
Wiring up modal ads to the 'again' button here is, like, 80% done.

**Comment by lazerwalker** [comment]
I've tested the modal ad flow, so closing this out
