### ISSUE TITLE
Disallow duplicate names

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#49]
I strongly suspect this is more work than we care about doing.

In general, I don't think people would particularly care about pretending to be someone else, but (a) I want to avoid confusion of multiple people having the same name, and (b) I can see an abuse vector where someone might want to churn through somebody else's daily Trial runs.

For the sake of argument, this would mean:

* Firebase maintains a list of all usernames
* When you type in a username, we check if it exists, and have UI to warn you if it's taken
* When you leave the settings page, we check if your username is valid. If yes, we call a Firebase function that (a) adds it to the DB and (b) removes your old username from the DB. If it's not valid, we revert you back to your old username

Where this gets complicated: if we naively assume the request went through, then people could easily cheese this and submit high scores as someone else. We could make the name change network request synchronous, but Firebase function cold start times make this awkward. Likely the right thing to do would be to store a tuple of `(username, unique ID)` and only accept scores for a given username if they also contain that unique ID. 

Alternatively, Firebase has a whole authentication system, but that feels heavy for what we're doing.

Again, I strongly suspect we just don't care about this for now, but putting this up for posterity

**Comment by orta** [comment]
Yeah, I wonder if we can do some anti-swear word validations in there - but I also think this is probably not worth the full effort for dupes 

If we do this then we may swell have real accounts for everyone

**Comment by lazerwalker** [comment]
One tester was annoyed that they set a high score, changed their name, and then couldn't re-"claim" their old high score. 

Still don't think a proper user auth system is worth the effort, but worth noting.

**Comment by lazerwalker** [comment]
Closing this out, https://github.com/lazerwalker/flappy-royale/issues/192 is now the relevant issue.
