### ISSUE TITLE
Share button should (ideally) share a screenshot

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#53]
Perhaps we can use https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by lazerwalker** [comment]
`navigator.share` doesn't support images. Given #52, I propose our own native share functions (on iOS/Android) get passed an image URL taken via https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by orta** [comment]
👍

**Comment by lazerwalker** [comment]
canvas.toDataURL() totally gives us a (slightly blurry :/) screenshot, but looking at that, it's clear we want something more custom that has e.g. the game's logo in it.

So, first step here is generating a share UI that shares a screenshot, and then next step is probably writing a canvas renderer that quickly makes + screenshots a more share-friendly image.

**Comment by orta** [comment]
This is in for iOS - I used the wkwebview API from native a933d4c

**Comment by lazerwalker** [comment]
woahhh, that's super-handy
