### ISSUE TITLE
In app: I can't change name anymore

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#57]
Don't think I touched anything related to this in the JS, but could be a weird side effect

**Comment by lazerwalker** [comment]
+1, seeing the same thing.

**Comment by orta** [comment]
I bet this is because of the user-select-none - https://github.com/lazerwalker/flappy-royale/commit/8f940112b9a9fbbdf63ad590c0c952f1e4980fe7

**Comment by lazerwalker** [comment]
Your fix is working for me!
