### ISSUE TITLE
Replace 'share' text with share icon?

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#66]
After a bunch of playtesting today, I made the play again button on the Royale death screen way bigger — everyone I handed the game to kept tapping share by mistake when they meant to restart.

I'm not yet happy with how the 'share' button looks. Might be some pixel-pushing will make it happier, but I suspect it would look better if we designed a share icon (e.g. box-with-an-upwards-arrow) that looks in line with our typography?

![IMG_1750](https://user-images.githubusercontent.com/821238/59165066-2357aa80-8b16-11e9-944e-71ae26ab641d.PNG)

**Comment by orta** [comment]
Yeah, I think ^ sorta thing can make sense, it might need a different color if it's onscreen and tappable 👍

**Comment by orta** [comment]
This is in
