### ISSUE TITLE
Loading a mode from the main menu sometimes leads to an empty blue screen

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#70]
I suspect this is related to intermittent poor network connectivity — good enough to load the game, not good enough to fetch seeds data?

**Comment by orta** [comment]
This might have been a bad deploy - today I was getting that constantly till I deployed the function

**Comment by orta** [comment]
I've not seen this on device lately

**Comment by lazerwalker** [comment]
Ditto, happy to close this out now and we can reopen it if ti shows up again after we've had folks banging on it
