### ISSUE TITLE
Improvements to trial death screen

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#77]
From #47 

- A "see leaderboard" button, instead of making you go all the way back to the main menu
- What the #1 score is, and what their name is
- What the score 1 position above yours is ("just get 3 more points to overtake Orta!")

**Comment by orta** [comment]
This is probably the best design I've seen for this sort of screen: 

![IMG_5485](https://user-images.githubusercontent.com/49038/59441068-d7726300-8dac-11e9-9d55-30dd505b1981.jpg)

**Comment by orta** [comment]
3 states: 

### You aren't top 3

![Artboard Copy 26](https://user-images.githubusercontent.com/49038/59447579-5325dd00-8db8-11e9-881c-f7e8c9c0fef5.png)

### 2nd or third

![Artboard Copy 27](https://user-images.githubusercontent.com/49038/59447605-5f119f00-8db8-11e9-95aa-04685d04f093.png)

( maybe change "again" to "almost" )?

### 1st (and top score for trial )

![Artboard Copy 29](https://user-images.githubusercontent.com/49038/59447628-6a64ca80-8db8-11e9-89dc-b45e304c3958.png)
