### ISSUE TITLE
"Thanks for watching an ad!" alert should be prettier

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#78]
Would like it to have both a bold title and not-bold body, which means threading through our own custom UIAlertController function rather than using my handler for JS `alert`.

Should be quick, but low-priority.

**Comment by orta** [comment]
We have a JS alert now!

**Comment by lazerwalker** [comment]
Yeah, it’s just a UIAlertController that shoves the text in as the bold title. 

Was imagining a custom method that would let us specify both the title and message of the alert controller so we can have some text bold and some not-bold.

**Comment by lazerwalker** [comment]
We can switch this over to the new in-engine modal prompts.

**Comment by lazerwalker** [comment]
Closed via c8f95cc4d4c552b96148bf1bb0e3f557006e4a64
