### ISSUE TITLE
Wait time for restarting Royale is infuriatingly slow

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#81]
Something I've consistently seen across playtests. People go to play Trial just because the restart loop is quicker.

Current thought: when you click 'again' on the death screen, we show an inline 1-2 second countdown to simulate "yeah, everyone else is clicking again right now" without taking you to the lobby?

Not yet sure I'm willing to give up on having some sort of timer (and the illusion of having other live players you're waiting for), but I could see us eventually doing that too.

**Comment by orta** [comment]
I agree - maybe new could make it say "matchmaking" somewhere to really give that impression (and also to dl the next set of seeds)
