### ISSUE TITLE
Mouse should work as flap in web build

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#89]

**Comment by lazerwalker** [comment]
Assuming we don't want to fork the input code between the builds: the trick here is to support both touch events and mouse events, but call either `e.preventDefault()` or `e.stopPropagation()` (don't remember) from the touch events so they don't bubble up into mouse events if touch is supported.

Note to self: Stephen just dealt with this in https://github.com/increpare/flickgame, so there's a commit within the last week that should be a good example.

**Comment by orta** [comment]
I added this I thought

**Comment by lazerwalker** [comment]
ah, cool, yeah, it's working. dunno what happened earlier.
