### ISSUE TITLE
Automate screenshots via Fastlane

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#90]
I've been looking for an excuse to figure out what this means when your entire app is driven by a webview.

Lazy solution is to expose Swift functions that call JS functions that manually set up the world the way we want it, but I'm personally interested in throwing some time to see if there's a not-horrific way to bridge browser automation and normal iOS automation.

(I'm having flashbacks to dispatching fake touch events at the libpurple level for https://github.com/lazerwalker/capybara-touch :P)

**Comment by lazerwalker** [comment]
I'm still trying to sort out the best way to do this. I think just having JS/Swift methods to set up the game is simplest, but unclear if there's a good pattern to do that given fastlane snapshot uses XCUI tests and they run out-of-process from the actual app.

In the meanwhile, what I'm shooting for is having screenshots for:

* Main menu
* Battle royale lobby with 99 players and no default names
* In-game
* Trial death screen with a decent high score
* Attire selection screen

Would be cool to set up more marketing-y framing (e.g. big honking text on the attire selection screen saying "LOOK YOU CAN WEAR COOL HATS") but I think this'll be 👍for a v1

**Comment by lazerwalker** [comment]
A really fucking cool thing I learned: XCUITests fully support web views! We still need to futz around manually because we're canvas based, but in theory if our menus were all DOM we could write Swift code to say "click the text ROYALE"

**Comment by lazerwalker** [comment]
Getting there! 3/5 are working, although the last two will be the most work:

<img width="718" alt="Screen Shot 2019-06-19 at 14 04 35" src="https://user-images.githubusercontent.com/821238/59764109-5d097d80-929b-11e9-9969-230d4dfce6c8.png">

**Comment by orta** [comment]
Hah, nice!

**Comment by lazerwalker** [comment]
We've got nice screenshots!
