### ISSUE TITLE
Also support webm for the video

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#91]
Or maybe the Firebase file Hosting or whatever

**Comment by lazerwalker** [comment]
if the concern is bandwidth rather than storage, we can also offer a webm version for supported browsers. Doesn't work in Safari, but'll be a solid order of magnitude smaller.

**Comment by orta** [comment]
I'm open to also having that - I fixed the mp4 in 8290bae but will change this to be having a web version
