### ISSUE TITLE
Add ad libraries to Android

### ISSUE THREAD

**Issue by lazerwalker** [flappy-royale/flappy-royale#93]
Not a blocker to iOS TestFlight, but will want before we do an Android beta distribution

**Comment by lazerwalker** [comment]
@orta I'm working on this, but would be nice if I could get added to Mopub (or wherever else I need to for dashboard access)

**Comment by lazerwalker** [comment]
Ignore me, found the creds :)

**Comment by lazerwalker** [comment]
Ignore me, found the creds :)

The one exception is AdMob, which I suspect is linked to your Google Account? Looks like you should be able to link it to the Firebase app.

**Comment by orta** [comment]
I couldn't add AdMob because it needs to be tied to a public app before I could do it, so I will as soon as possible

**Comment by lazerwalker** [comment]
This is theoretically working, but I can't actually get any ad inventory.

Gonna switch to something else til I can check in with you about whether there's something you had to do on iOS, but one other thing I probably want to add at some point is pre-warming the ads. The Android docs suggest an API method to call e.g. when we show the user the trial death screen in the case the user has no lives that prefetches the ad. 

It's possible the reason I'm not getting inventory is because the Android methods are explicitly checking if there's anything cached. If not, still seems like a sensible thing to do.

**Comment by lazerwalker** [comment]
The test banner ad works!

Video ads are close to working, but I can't get any inventory with either a real ID or the test ID. I wonder if there's any trick you had to do for iOS that's not obvious from the code?

Other new thing I'm doing on Android: based on their docs, I'm asking MoPub to preload a video ad when the user might want one (e.g. whenever we load the trial lobby or death screen and the user has 0 lives). This was still broken before that — was hoping this would fix the no inventory issue, but no dice.
